services:
    youtube_live_alert:
        build: .
        image: youtube_live_alert
        container_name: youtube_live_alert
        volumes:
            - ./conf:/youtube_live_alert/conf
        restart: always
